In [14]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
import matplotlib.pyplot as plt
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

In [2]:
df_drug=pd.read_csv('DTA/UniqueDrug_CBF_Train.csv')
df_pro=pd.read_csv("DTA/UniqueProt_PBF_Train.csv")
df_inter=pd.read_csv("DTA/InteractionsMapping_Train (2).csv")
df_drug_test=pd.read_csv('DTA/UniqueDrug_CBF_Test.csv')
df_pro_test=pd.read_csv("DTA/UniqueProt_PBF_Test.csv")
df_inter_test=pd.read_csv("DTA/InteractionsMapping_Test (2).csv")

In [3]:
for i in range(768):
    df_drug_test=df_drug_test.rename(columns={str(i):"CBF"+str((i+1))})
df_drug_test.head()

Drug_ID                                             SMILES      CBF1  \
0  ZINC16051658                  CC1=NN=C(O1)C2C(C(C(C(O2)CO)O)O)O  0.637852   
1       DB00683    CC1=NC=C2N1C3=C(C=C(C=C3)Cl)C(=NC2)C4=CC=CC=C4F  0.511134   
2       DB00491                           C1C(C(C(C(N1CCO)CO)O)O)O  1.009394   
3           ARA                               C1C(C(C(C(O1)O)O)O)O  0.738805   
4       DB00430  CC1=CC(=O)C(=CN1)C(=O)NC(C2=CC=C(C=C2)O)C(=O)N...  0.432591   

       CBF2      CBF3      CBF4      CBF5      CBF6      CBF7      CBF8  ...  \
0  0.025078 -0.137181  0.220558  0.985396 -0.497337 -0.323126  0.108800  ...   
1  0.610606  0.014891 -0.301693  1.006940 -0.066792 -0.333556 -0.011036  ...   
2 -0.483389  0.251511  0.248934  0.956376 -0.310975 -0.287940  0.057785  ...   
3 -0.497518 -0.214917  0.252138  1.002670 -0.425593 -0.379717  0.063613  ...   
4 -0.156011 -0.739867  0.043201  0.614482 -0.497177 -0.644078 -0.063058  ...   

     CBF759    CBF760    CBF761    CBF762    CBF763    CBF764    CBF765  \
0  0.113765  0.303574  0.383457 -0.047252 -0.429677  0.569537 -0.275597   
1  0.010872  0.307153 -0.626864 -0.053657 -0.850919  1.168610 -0.034645   
2  0.383068  0.624767  0.370716  0.472160 -0.241153  0.216597 -0.484063   
3  0.531138  0.861370  0.393844  0.111346  0.050331  0.533231 -0.227467   
4 -0.099798  0.148621 -0.086503 -0.565915 -0.574261  0.783125 -0.110612   

     CBF766    CBF767    CBF768  
0 -0.370870  0.060566  0.977041  
1 -0.211338 -0.247332  0.665498  
2 -0.499242  0.252377  0.608097  
3 -0.513811  0.507615  0.945831  
4 -0.025541 -0.386042  0.759858  

[5 rows x 770 columns]

In [4]:
merge_df=df_inter.merge(df_drug, on='Drug_ID' , how='inner')
merge_df=merge_df.merge(df_pro,on='P_ID', how='inner')
merge_df_test=df_inter_test.merge(df_drug_test, on='Drug_ID' , how='inner')
merge_df_test=merge_df_test.merge(df_pro_test,on='P_ID', how='inner')
merge_df =merge_df.sample(frac=1).reset_index(drop=True)
merge_df_test =merge_df_test.sample(frac=1).reset_index(drop=True) 
merge_df.to_csv('train.csv', index=False) 
 

In [5]:
X = merge_df.drop(columns=['Labels', 'P_ID', 'Drug_ID','SMILES','Sequence'])
y=merge_df['Labels']
X_test = merge_df_test.drop(columns=['Labels', 'P_ID', 'Drug_ID','SMILES','Sequence'])
y_test=merge_df_test['Labels']

In [6]:
clf=RandomForestClassifier(n_estimators=78,ccp_alpha=0.000015,random_state=42,min_impurity_decrease=0.0000052,max_leaf_nodes=400,class_weight="balanced_subsample")
#clf=RandomForestClassifier(verbose=3,n_estimators=78,ccp_alpha=0.00001,random_state=42,min_impurity_decrease=0.0000012) 93.47
#clf=RandomForestClassifier(verbose=3,n_estimators=78,ccp_alpha=0.000015,random_state=42,min_impurity_decrease=0.0000052) 93.54
#clf=RandomForestClassifier(verbose=3,n_estimators=78,ccp_alpha=0.000015,random_state=42,min_impurity_decrease=0.0000052,max_leaf_nodes=400) 93.603

In [7]:
clf.fit(X,y)


RandomForestClassifier(ccp_alpha=1.5e-05, class_weight='balanced_subsample',
                       max_leaf_nodes=400, min_impurity_decrease=5.2e-06,
                       n_estimators=78, random_state=42)

In [8]:
y_predict=clf.predict(X_test)

In [9]:
acc_score=accuracy_score(y_test,y_predict)
acc_score

0.9288417865253595

In [10]:
 from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
# Compute confusion matrix
cm = confusion_matrix(y_test, y_predict)
print(cm)
# Plot confusion matrix
"""plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=['Class 0', 'Class 1'], yticklabels=['Class 0', 'Class 1'])
plt.title('Confusion Matrix')
plt.xlabel('Predicted')
plt.ylabel('True 
plt.show()"""

[[4860   54]
 [ 510 2502]]


"plt.figure(figsize=(8, 6))\nsns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=['Class 0', 'Class 1'], yticklabels=['Class 0', 'Class 1'])\nplt.title('Confusion Matrix')\nplt.xlabel('Predicted')\nplt.ylabel('True \nplt.show()"

In [13]:
clf=RandomForestClassifier(verbose=3,n_estimators=78,ccp_alpha=0.000015,random_state=42,min_impurity_decrease=0.0000052,min_samples_split=5,max_features=800)
clf.fit(X_train_resampled, y_train_resampled)
y_predict=clf.predict(X_test)
acc_score=accuracy_score(y_test,y_predict)
acc_score 

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


building tree 1 of 78


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:   14.7s remaining:    0.0s


building tree 2 of 78


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:   29.6s remaining:    0.0s


building tree 3 of 78
building tree 4 of 78
building tree 5 of 78
building tree 6 of 78
building tree 7 of 78
building tree 8 of 78
building tree 9 of 78
building tree 10 of 78
building tree 11 of 78
building tree 12 of 78
building tree 13 of 78
building tree 14 of 78
building tree 15 of 78
building tree 16 of 78
building tree 17 of 78
building tree 18 of 78
building tree 19 of 78
building tree 20 of 78
building tree 21 of 78
building tree 22 of 78
building tree 23 of 78
building tree 24 of 78
building tree 25 of 78
building tree 26 of 78
building tree 27 of 78
building tree 28 of 78
building tree 29 of 78
building tree 30 of 78
building tree 31 of 78
building tree 32 of 78
building tree 33 of 78
building tree 34 of 78
building tree 35 of 78
building tree 36 of 78
building tree 37 of 78
building tree 38 of 78
building tree 39 of 78
building tree 40 of 78
building tree 41 of 78
building tree 42 of 78
building tree 43 of 78
building tree 44 of 78
building tree 45 of 78
building tree 46 o

[Parallel(n_jobs=1)]: Done  78 out of  78 | elapsed: 32.6min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  78 out of  78 | elapsed:    0.1s finished


0.9288417865253595

In [17]:
cm= confusion_matrix(y_test, y_predict)
print(cm)
print("Accuracy:", accuracy_score(y_test, y_predict))
precision = precision_score(y_test, y_predict )
recall = recall_score(y_test, y_predict)
f1 = f1_score(y_test, y_predict)
accuracy = accuracy_score(y_test, y_predict)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)
print("Accuracy:", accuracy)


[[4855   59]
 [ 505 2507]]
Accuracy: 0.9288417865253595
Precision: 0.9770070148090413
Recall: 0.8323373173970784
F1-score: 0.8988884904983865
Accuracy: 0.9288417865253595


In [18]:
clf=RandomForestClassifier(verbose=3,n_estimators=78,ccp_alpha=0.000015,random_state=42,min_impurity_decrease=0.0000052,max_leaf_nodes=400) 
clf.fit(X_train_resampled, y_train_resampled)
y_predict=clf.predict(X_test)
acc_score=accuracy_score(y_test,y_predict)
cm= confusion_matrix(y_test, y_predict)
print(cm)
print("Accuracy:", accuracy_score(y_test, y_predict))
precision = precision_score(y_test, y_predict )
recall = recall_score(y_test, y_predict)
f1 = f1_score(y_test, y_predict)
accuracy = accuracy_score(y_test, y_predict)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)
print("Accuracy:", accuracy)


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


building tree 1 of 78


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.6s remaining:    0.0s


building tree 2 of 78


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    1.1s remaining:    0.0s


building tree 3 of 78
building tree 4 of 78
building tree 5 of 78
building tree 6 of 78
building tree 7 of 78
building tree 8 of 78
building tree 9 of 78
building tree 10 of 78
building tree 11 of 78
building tree 12 of 78
building tree 13 of 78
building tree 14 of 78
building tree 15 of 78
building tree 16 of 78
building tree 17 of 78
building tree 18 of 78
building tree 19 of 78
building tree 20 of 78
building tree 21 of 78
building tree 22 of 78
building tree 23 of 78
building tree 24 of 78
building tree 25 of 78
building tree 26 of 78
building tree 27 of 78
building tree 28 of 78
building tree 29 of 78
building tree 30 of 78
building tree 31 of 78
building tree 32 of 78
building tree 33 of 78
building tree 34 of 78
building tree 35 of 78
building tree 36 of 78
building tree 37 of 78
building tree 38 of 78
building tree 39 of 78
building tree 40 of 78
building tree 41 of 78
building tree 42 of 78
building tree 43 of 78
building tree 44 of 78
building tree 45 of 78
building tree 46 o

[Parallel(n_jobs=1)]: Done  78 out of  78 | elapsed:   45.7s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  78 out of  78 | elapsed:    0.0s finished


In [19]:
clf=RandomForestClassifier(verbose=3,n_estimators=78,ccp_alpha=0.000015,random_state=42,min_impurity_decrease=0.0000052) 
clf.fit(X_train_resampled, y_train_resampled)
y_predict=clf.predict(X_test)
acc_score=accuracy_score(y_test,y_predict)
cm= confusion_matrix(y_test, y_predict)
print(cm)
print("Accuracy:", accuracy_score(y_test, y_predict))
precision = precision_score(y_test, y_predict )
recall = recall_score(y_test, y_predict)
f1 = f1_score(y_test, y_predict)
accuracy = accuracy_score(y_test, y_predict)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)
print("Accuracy:", accuracy)


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


building tree 1 of 78


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s


building tree 2 of 78


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    1.0s remaining:    0.0s


building tree 3 of 78
building tree 4 of 78
building tree 5 of 78
building tree 6 of 78
building tree 7 of 78
building tree 8 of 78
building tree 9 of 78
building tree 10 of 78
building tree 11 of 78
building tree 12 of 78
building tree 13 of 78
building tree 14 of 78
building tree 15 of 78
building tree 16 of 78
building tree 17 of 78
building tree 18 of 78
building tree 19 of 78
building tree 20 of 78
building tree 21 of 78
building tree 22 of 78
building tree 23 of 78
building tree 24 of 78
building tree 25 of 78
building tree 26 of 78
building tree 27 of 78
building tree 28 of 78
building tree 29 of 78
building tree 30 of 78
building tree 31 of 78
building tree 32 of 78
building tree 33 of 78
building tree 34 of 78
building tree 35 of 78
building tree 36 of 78
building tree 37 of 78
building tree 38 of 78
building tree 39 of 78
building tree 40 of 78
building tree 41 of 78
building tree 42 of 78
building tree 43 of 78
building tree 44 of 78
building tree 45 of 78
building tree 46 o

[Parallel(n_jobs=1)]: Done  78 out of  78 | elapsed:   46.8s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  78 out of  78 | elapsed:    0.0s finished


In [21]:
clf=RandomForestClassifier(n_estimators=78,ccp_alpha=0.000015,random_state=42,min_impurity_decrease=0.0000052,min_samples_leaf=10) 
clf.fit(X_train_resampled, y_train_resampled)
y_predict=clf.predict(X_test)
acc_score=accuracy_score(y_test,y_predict)
cm= confusion_matrix(y_test, y_predict)
print(cm)
print("Accuracy:", accuracy_score(y_test, y_predict))
precision = precision_score(y_test, y_predict )
recall = recall_score(y_test, y_predict)
f1 = f1_score(y_test, y_predict)
accuracy = accuracy_score(y_test, y_predict)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)
print("Accuracy:", accuracy)


[[4825   89]
 [ 490 2522]]
Accuracy: 0.9269492808478426
Precision: 0.9659134431252394
Recall: 0.8373173970783533
F1-score: 0.8970300551307133
Accuracy: 0.9269492808478426


In [22]:
clf=RandomForestClassifier(n_estimators=78,ccp_alpha=0.000015,random_state=42,min_impurity_decrease=0.0000052,min_samples_leaf=8) 
clf.fit(X_train_resampled, y_train_resampled)
y_predict=clf.predict(X_test)
acc_score=accuracy_score(y_test,y_predict)
cm= confusion_matrix(y_test, y_predict)
print(cm)
print("Accuracy:", accuracy_score(y_test, y_predict))
precision = precision_score(y_test, y_predict )
recall = recall_score(y_test, y_predict)
f1 = f1_score(y_test, y_predict)
accuracy = accuracy_score(y_test, y_predict)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)
print("Accuracy:", accuracy)


[[4832   82]
 [ 496 2516]]
Accuracy: 0.9270754478930103
Precision: 0.968437259430331
Recall: 0.8353253652058433
F1-score: 0.896969696969697
Accuracy: 0.9270754478930103


In [23]:
clf=RandomForestClassifier(n_estimators=78,ccp_alpha=0.000015,random_state=42,min_impurity_decrease=0.0000052,min_samples_leaf=10,max_features=1000,class_weight={0:1,1:2}) 
clf.fit(X_train_resampled, y_train_resampled)
y_predict=clf.predict(X_test)
acc_score=accuracy_score(y_test,y_predict)
cm= confusion_matrix(y_test, y_predict)
print(cm)
print("Accuracy:", accuracy_score(y_test, y_predict))
precision = precision_score(y_test, y_predict )
recall = recall_score(y_test, y_predict)
f1 = f1_score(y_test, y_predict)
accuracy = accuracy_score(y_test, y_predict)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)
print("Accuracy:", accuracy)


[[4794  120]
 [ 488 2524]]
Accuracy: 0.9232904365379763
Precision: 0.9546142208774584
Recall: 0.8379814077025233
F1-score: 0.8925035360678925
Accuracy: 0.9232904365379763


In [24]:
clf=RandomForestClassifier(n_estimators=78,ccp_alpha=0.000015,random_state=42,min_impurity_decrease=0.0000052,min_samples_leaf=10,max_features=1700,class_weight={0:1,1:2}) 
clf.fit(X_train_resampled, y_train_resampled)
y_predict=clf.predict(X_test)
acc_score=accuracy_score(y_test,y_predict)
cm= confusion_matrix(y_test, y_predict)
print(cm)
print("Accuracy:", accuracy_score(y_test, y_predict))
precision = precision_score(y_test, y_predict )
recall = recall_score(y_test, y_predict)
f1 = f1_score(y_test, y_predict)
accuracy = accuracy_score(y_test, y_predict)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)
print("Accuracy:", accuracy)


[[4794  120]
 [ 486 2526]]
Accuracy: 0.9235427706283119
Precision: 0.9546485260770975
Recall: 0.8386454183266933
F1-score: 0.8928950159066809
Accuracy: 0.9235427706283119
