In [15]:
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report
from sklearn import tree
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification
from sklearn.decomposition import PCA
from mlxtend.plotting import plot_decision_regions
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

In [16]:
df_drug=pd.read_csv('DTA/UniqueDrug_CBF_Train.csv')
df_pro=pd.read_csv("DTA/UniqueProt_PBF_Train.csv")
df_inter=pd.read_csv("DTA/InteractionsMapping_Train (2).csv")
df_drug_test=pd.read_csv('DTA/UniqueDrug_CBF_Test.csv')
df_pro_test=pd.read_csv("DTA/UniqueProt_PBF_Test.csv")
df_inter_test=pd.read_csv("DTA/InteractionsMapping_Test (2).csv")

In [17]:
for i in range(768):
    df_drug_test=df_drug_test.rename(columns={str(i):"CBF"+str((i+1))})
df_drug_test.head()
df_drug.head()

Drug_ID                                             SMILES      CBF1  \
0        D00332                              C1CCC(CC1)(CC(=O)O)CN  0.037544   
1  ZINC27191322         C1=C(C(=O)NC(=O)N1CC(C(=O)O)N)[N+](=O)[O-] -0.258293   
2  ZINC96142463                CCCC(=O)C1=C(SC(C1=O)(C)C=C(C)C=C)O  0.321486   
3  ZINC13809235                  CCCC1N=C(N=C(N1C2=CC=C(C=C2)C)N)N  0.345021   
4  ZINC26475560  CC(C)N1CCC(C2=C1C=CC(=C2)C#CC3=CC=C(C=C3)C(=O)...  0.621289   

       CBF2      CBF3      CBF4      CBF5      CBF6      CBF7      CBF8  ...  \
0 -0.099144  0.531602 -1.092002  0.138534 -1.023876  0.052266  0.229308  ...   
1  0.238235 -0.223422  0.067166  0.067607 -0.600219 -0.459803  0.028299  ...   
2  0.002419  0.250102 -0.492102  0.697824 -0.383989 -0.253627 -0.136740  ...   
3  0.096738  0.557861 -0.297296  0.896446 -0.032985 -0.270661 -0.065642  ...   
4 -0.243912  0.133150 -0.270405  0.884132 -0.411581 -0.052357 -0.015780  ...   

     CBF759    CBF760    CBF761    CBF762    CBF763    CBF764    CBF765  \
0 -0.237594  0.063648 -0.361055 -0.789500 -0.465886 -0.529316 -0.698997   
1  0.098411  0.609853 -0.267673 -0.212289 -0.063081  0.234073 -0.327776   
2 -0.141038  0.050899 -0.037386  0.040839 -0.630284  0.954118  0.025331   
3  0.236711  0.737370 -0.518561  0.511849 -0.820826  1.201285  0.370854   
4  0.080137  0.141621 -0.015267 -0.466190 -0.924487  0.557753 -0.239291   

     CBF766    CBF767    CBF768  
0 -0.952023  0.655639  0.239113  
1 -0.777139 -0.068785  0.186652  
2 -0.314066 -0.411639  0.784826  
3 -0.434524 -0.433207  0.910684  
4 -0.065333 -0.234828  0.338684  

[5 rows x 770 columns]

In [18]:
merge_df=df_inter.merge(df_drug, on='Drug_ID' , how='inner')
merge_df=merge_df.merge(df_pro,on='P_ID', how='inner')
merge_df_test=df_inter_test.merge(df_drug_test, on='Drug_ID' , how='inner')
merge_df_test=merge_df_test.merge(df_pro_test,on='P_ID', how='inner')

In [19]:
X = merge_df.drop(columns=['Labels', 'P_ID', 'Drug_ID','SMILES','Sequence'])
y=merge_df['Labels']
X_test = merge_df_test.drop(columns=['Labels', 'P_ID', 'Drug_ID','SMILES','Sequence'])
y_test=merge_df_test['Labels']

In [20]:
sc = StandardScaler()
X = sc.fit_transform(X)
X_test = sc.transform(X_test)
svm_classifier = SVC(kernel='poly',random_state=42,C=2.45,)
svm_classifier.fit(X, y)
y_pred = svm_classifier.predict(X_test)
cm= confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy:", accuracy_score(y_test, y_pred))
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)
print("Accuracy:", accuracy)


[[4865   49]
 [ 582 2430]]
Accuracy: 0.9203885944991168
Precision: 0.9802339653085922
Recall: 0.8067729083665338
F1-score: 0.8850846840284102
Accuracy: 0.9203885944991168


linear  =90.24
poly = 91.96  c=2.5 ->92.038
rdf= 90.95    c=2.0 ->91.06 c=2.5->91.11 c=3.0-> 91.09 c=4.0 ->91.06

In [22]:

sc = StandardScaler()
X = sc.fit_transform(X)
X_test = sc.transform(X_test)
svm_classifier = SVC(kernel='rbf',random_state=42,C=2.45,)
svm_classifier.fit(X, y)
y_pred = svm_classifier.predict(X_test)
cm= confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy:", accuracy_score(y_test, y_pred))
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)
print("Accuracy:", accuracy)


[[4874   40]
 [ 664 2348]]
Accuracy: 0.9111784002018672
Precision: 0.983249581239531
Recall: 0.7795484727755644
F1-score: 0.8696296296296296
Accuracy: 0.9111784002018672


In [23]:

X = sc.fit_transform(X)
X_test = sc.transform(X_test)
svm_classifier = SVC(kernel='poly',degree=10,random_state=42,C=2.45,)
svm_classifier.fit(X, y)
y_pred = svm_classifier.predict(X_test)
cm= confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy:", accuracy_score(y_test, y_pred))
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)
print("Accuracy:", accuracy)


[[4888   26]
 [1751 1261]]
Accuracy: 0.7758011607368156
Precision: 0.9797979797979798
Recall: 0.41865869853917664
F1-score: 0.5866480576878345
Accuracy: 0.7758011607368156


In [26]:

X = sc.fit_transform(X)
X_test = sc.transform(X_test)
svm_classifier = SVC(kernel='rbf',decision_function_shape='ovr',random_state=42,C=2.45,)
svm_classifier.fit(X, y)
y_pred = svm_classifier.predict(X_test)
cm= confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy:", accuracy_score(y_test, y_pred))
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)
print("Accuracy:", accuracy)


[[4874   40]
 [ 664 2348]]
Accuracy: 0.9111784002018672
Precision: 0.983249581239531
Recall: 0.7795484727755644
F1-score: 0.8696296296296296
Accuracy: 0.9111784002018672


In [27]:

X = sc.fit_transform(X)
X_test = sc.transform(X_test)
svm_classifier = SVC(kernel='poly',decision_function_shape='ovr',random_state=42,C=2.45,)
svm_classifier.fit(X, y)
y_pred = svm_classifier.predict(X_test)
cm= confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy:", accuracy_score(y_test, y_pred))
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)
print("Accuracy:", accuracy)


[[4865   49]
 [ 582 2430]]
Accuracy: 0.9203885944991168
Precision: 0.9802339653085922
Recall: 0.8067729083665338
F1-score: 0.8850846840284102
Accuracy: 0.9203885944991168


In [29]:

X = sc.fit_transform(X)
X_test = sc.transform(X_test)
svm_classifier = SVC(kernel='poly',decision_function_shape='ovr',random_state=42,C=2.45,class_weight={0:1,1:1.745},)
svm_classifier.fit(X, y)
y_pred = svm_classifier.predict(X_test)
cm= confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy:", accuracy_score(y_test, y_pred))
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)
print("Accuracy:", accuracy)


[[4844   70]
 [ 560 2452]]
Accuracy: 0.9205147615442847
Precision: 0.972244250594766
Recall: 0.8140770252324038
F1-score: 0.886158294181424
Accuracy: 0.9205147615442847


In [30]:

X = sc.fit_transform(X)
X_test = sc.transform(X_test)
svm_classifier = SVC(kernel='poly',decision_function_shape='ovo',random_state=42,C=2.45,class_weight={0:1,1:1.745},)
svm_classifier.fit(X, y)
y_pred = svm_classifier.predict(X_test)
cm= confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy:", accuracy_score(y_test, y_pred))
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)
print("Accuracy:", accuracy)


[[4844   70]
 [ 560 2452]]
Accuracy: 0.9205147615442847
Precision: 0.972244250594766
Recall: 0.8140770252324038
F1-score: 0.886158294181424
Accuracy: 0.9205147615442847


In [33]:

X = sc.fit_transform(X)
X_test = sc.transform(X_test)
svm_classifier = SVC(kernel='rbf',gamma=0.05,decision_function_shape='ovo',random_state=42,C=2.45,class_weight={0:1,1:1.745},)
svm_classifier.fit(X, y)
y_pred = svm_classifier.predict(X_test)
cm= confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy:", accuracy_score(y_test, y_pred))
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)
print("Accuracy:", accuracy)


[[4902   12]
 [2393  619]]
Accuracy: 0.6965682563714358
Precision: 0.9809825673534073
Recall: 0.2055112881806109
F1-score: 0.339829810595663
Accuracy: 0.6965682563714358
